export const elements ={
    name : '#name',
    birthdate: '#birthdate',
    location: '#location',
    city: '#city',
    username: '#username',
    email: '#email',
    password: '#password',
    confirmPwd: '#confirmed-password',
    nextBtn: 'a > .h-12',
    sexInden: '#sexident',
    sexPrefer: '#sexprefer',
    racialPrefer: '#racialprefer',
    meeting: '#meetprefer',
    hobby: '#hobby',
    usernameOrEmail : '#username-email',
    password: '#password',
}
